

CREATE TABLE admin_users (
 id INT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(100) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 first_name VARCHAR(50) NOT NULL,
 last_name VARCHAR(50) NOT NULL,
 phone VARCHAR(20),
 role_id INT NOT NULL,
 is_active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
 FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE customers (
 id INT PRIMARY KEY AUTO_INCREMENT,
 email VARCHAR(100) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 first_name VARCHAR(50) NOT NULL,
 last_name VARCHAR(50) NOT NULL,
 phone VARCHAR(20) NOT NULL,
 date_of_birth DATE,
 is_active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP
);

CREATE TABLE customer_addresses (
 id INT PRIMARY KEY AUTO_INCREMENT,
 customer_id INT NOT NULL,
 alias VARCHAR(50) NOT NULL,
 street_address VARCHAR(200) NOT NULL,
 city VARCHAR(100) NOT NULL,
 state VARCHAR(100) NOT NULL,
 postal_code VARCHAR(20),
 country VARCHAR(100) DEFAULT 'Costa Rica',
 additional_info TEXT,
 is_default BOOLEAN DEFAULT FALSE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
 FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE roles (
 id INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(50) NOT NULL UNIQUE,
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP
);

CREATE TABLE products (
 id INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(200) NOT NULL,
 description TEXT,
 price DECIMAL(10,2) NOT NULL,
 category_id INT,
 stock_quantity INT DEFAULT 0,
 min_stock_level INT DEFAULT 0,
 image_url VARCHAR(255),
 is_active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
 FOREIGN KEY (category_id) REFERENCES product_categories(id)
);

CREATE TABLE product_categories (
 id INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 description TEXT,
 image_url VARCHAR(255),
 is_active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP
);

CREATE TABLE orders (
 id INT PRIMARY KEY AUTO_INCREMENT,
 order_number VARCHAR(50) NOT NULL UNIQUE,
 customer_id INT NOT NULL,
 address_id INT NOT NULL,
 status_id INT NOT NULL,
 subtotal DECIMAL(10,2) NOT NULL,
 tax_amount DECIMAL(10,2) DEFAULT 0,
 shipping_cost DECIMAL(10,2) DEFAULT 0,
 discount_amount DECIMAL(10,2) DEFAULT 0,
 total_amount DECIMAL(10,2) NOT NULL,
 notes TEXT,
 admin_notes TEXT,
 estimated_delivery DATETIME,
 delivered_at DATETIME,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
 FOREIGN KEY (customer_id) REFERENCES customers(id),
 FOREIGN KEY (address_id) REFERENCES customer_addresses(id),
 FOREIGN KEY (status_id) REFERENCES order_statuses(id)
);

CREATE TABLE order_items (
 id INT PRIMARY KEY AUTO_INCREMENT,
 order_id INT NOT NULL,
 product_id INT NOT NULL,
 quantity INT NOT NULL,
 unit_price DECIMAL(10,2) NOT NULL,
 total_price DECIMAL(10,2) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE order_status_history (
 id INT PRIMARY KEY AUTO_INCREMENT,
 order_id INT NOT NULL,
 status_id INT NOT NULL,
 changed_by INT,
 notes TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY (status_id) REFERENCES order_statuses(id),
 FOREIGN KEY (changed_by) REFERENCES admin_users(id)
);

CREATE TABLE order_statuses (
 id INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(50) NOT NULL UNIQUE,
 description VARCHAR(200),
 color VARCHAR(7) DEFAULT '#000000',
 order_sequence INT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shopping_cart (
 id INT PRIMARY KEY AUTO_INCREMENT,
 customer_id INT NOT NULL,
 product_id INT NOT NULL,
 quantity INT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
 FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
 UNIQUE KEY unique_customer_product (customer_id, product_id)
);

CREATE TABLE system_settings (
 id INT PRIMARY KEY AUTO_INCREMENT,
 setting_key VARCHAR(100) NOT NULL UNIQUE,
 setting_value TEXT,
 description TEXT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP
); 